---
- name: install cockpit
  hosts: all
  tasks:
    - name: install package
      package:
        name: cockpit
        state: present
    - name: start the service
      service: 
        name: cockpit
        state: started
        enabled: true
    - name: open firewall
      firewalld:
        service: cockpit
        permanent: yes
        state: enabled